# Generated by Django 5.0.2 on 2024-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0004_rename_appointment_type_appointment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
