# Generated by Django 5.0.2 on 2024-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0011_prescription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='test',
        ),
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='Diagnostic_Center.test'),
        ),
    ]
