# Generated by Django 5.0.2 on 2024-03-13 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0012_remove_prescription_test_prescription_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='test',
        ),
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.test'),
        ),
    ]
