# Generated by Django 5.0.2 on 2024-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0014_remove_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pres_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
