# Generated by Django 4.2.6 on 2024-03-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0016_remove_prescription_pres_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='date1',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='text1',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
