# Generated by Django 4.2.6 on 2024-03-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diagnostic_Center', '0017_remove_prescription_date1_alter_prescription_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pres_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
