# Generated by Django 4.2.6 on 2024-03-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0024_attendentprofile'),
        ('Diagnostic_Center', '0018_prescription_date1_prescription_pres_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pres_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Login.doctor'),
        ),
    ]
