# Generated by Django 4.2.6 on 2024-03-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0024_attendentprofile'),
        ('Diagnostic_Center', '0019_prescription_pres_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pres_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Login.dcmpatient'),
        ),
    ]
