# Generated by Django 4.2.6 on 2024-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0021_prescription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date1',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
