# Generated by Django 4.2.6 on 2024-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0022_alter_prescription_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_test',
            field=models.ManyToManyField(blank=True, null=True, to='Diagnostic_Center.test'),
        ),
    ]
