# Generated by Django 4.2.6 on 2024-03-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0023_package_package_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='time1',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
