# Generated by Django 4.2.6 on 2024-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0024_remove_doctorappointment_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
