# Generated by Django 4.2.6 on 2024-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0025_doctorappointment_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
