# Generated by Django 4.2.6 on 2024-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0026_alter_doctorappointment_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetestappointment',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='testappointment',
            name='time1',
        ),
        migrations.AddField(
            model_name='packagetestappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='packagetestappointment',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
