# Generated by Django 4.2.6 on 2024-03-31 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0027_remove_packagetestappointment_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='Diagnostic_Center.test'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_price', models.IntegerField(null=True)),
                ('medicine_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.department')),
            ],
        ),
    ]
