# Generated by Django 4.2.6 on 2024-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0028_prescription_test_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(blank=True, null=True, to='Diagnostic_Center.medicine'),
        ),
    ]
