# Generated by Django 4.2.6 on 2024-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0029_prescription_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='Diagnostic_Center.test'),
        ),
    ]
