# Generated by Django 4.2.6 on 2024-04-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0030_testappointment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetestappointment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.package'),
        ),
    ]
