# Generated by Django 4.2.6 on 2024-04-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('Diagnostic_Center', '0031_packagetestappointment_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
