# Generated by Django 4.2.6 on 2024-04-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0032_alter_medicine_medicine_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Confirmed', max_length=20, null=True),
        ),
    ]
