# Generated by Django 4.2.6 on 2024-04-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('Diagnostic_Center', '0040_alter_packagetestappointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='test_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.department'),
        ),
        migrations.RemoveField(
            model_name='testappointment',
            name='test',
        ),
        migrations.AddField(
            model_name='testappointment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.test'),
        ),
    ]
