# Generated by Django 4.2.6 on 2024-05-09 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Login', '0035_doctor_profile_pic'),
        ('Diagnostic_Center', '0041_testappointment_test_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=800, null=True)),
                ('date', models.DateField()),
                ('report_status', models.CharField(blank=True, choices=[('On Progress', 'On Progress'), ('Publish', 'Publish')], default='On Progress', max_length=30, null=True)),
                ('appointment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.testappointment')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Login.dcmpatient')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.test')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=800, null=True)),
                ('date', models.DateField()),
                ('report_status', models.CharField(blank=True, choices=[('On Progress', 'On Progress'), ('Publish', 'Publish')], default='On Progress', max_length=30, null=True)),
                ('Package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.package')),
                ('appointment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnostic_Center.packagetestappointment')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Login.dcmpatient')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
