# Generated by Django 4.2.6 on 2024-05-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostic_Center', '0042_testreport_packagetestreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='report'),
        ),
    ]
