# Generated by Django 5.0.2 on 2024-02-22 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_alter_doctor_user_alter_pathologist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcmPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('pcreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcmpatient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
