# Generated by Django 5.0.2 on 2024-02-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_dcmpatient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='DcmAdmin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_pathologist',
            new_name='is_dcmadmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.DeleteModel(
            name='Pathologist',
        ),
    ]
