# Generated by Django 5.0.2 on 2024-02-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_remove_user_user_type_doctor_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_first_name',
            new_name='doctor_full_nane',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_last_name',
        ),
    ]
