# Generated by Django 5.0.2 on 2024-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0007_rename_doctor_first_name_doctor_doctor_full_nane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_full_nane',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
