# Generated by Django 5.0.2 on 2024-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_remove_doctor_doctor_full_nane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='job_position',
            field=models.CharField(blank=True, choices=[('pathologist', 'pathologist'), ('Sample Collector', 'Sample Collector'), ('Receptionist', 'Receptionist')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
