# Generated by Django 5.0.2 on 2024-02-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_technician_job_position_technician_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='job_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
