# Generated by Django 5.0.2 on 2024-03-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0012_alter_dcmpatient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcmpatient',
            old_name='pcreator',
            new_name='user',
        ),
    ]
