# Generated by Django 5.0.2 on 2024-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0013_rename_pcreator_dcmpatient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='job_position',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_full_name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='current_working_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mbbs_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='post_graduation_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='spe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
