# Generated by Django 5.0.2 on 2024-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0014_rename_job_position_technician_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
