# Generated by Django 5.0.2 on 2024-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0017_rename_name_technician_technician_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
