# Generated by Django 5.0.2 on 2024-03-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0018_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
