# Generated by Django 5.0.2 on 2024-03-11 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0020_doctorprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='technician',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='App_Login.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('technician', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to='App_Login.technician')),
            ],
        ),
    ]
