# Generated by Django 5.0.2 on 2024-03-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0022_attendent_user_is_attendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmpatient',
            name='attendent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendent_profile', to='App_Login.attendent'),
        ),
    ]
