# Generated by Django 4.2.6 on 2024-03-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0024_attendentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcmpatient',
            name='attendent',
        ),
        migrations.AddField(
            model_name='dcmpatient',
            name='slug',
            field=models.SlugField(blank=True, max_length=264, null=True, unique=True),
        ),
    ]
