# Generated by Django 4.2.6 on 2024-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0025_remove_dcmpatient_attendent_dcmpatient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmpatient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
