# Generated by Django 4.2.6 on 2024-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0028_alter_dcmpatient_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmpatient',
            name='patient_blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True),
        ),
    ]
