# Generated by Django 4.2.6 on 2024-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0029_alter_dcmpatient_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmpatient',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dcmpatient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcmpatient',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
