# Generated by Django 4.2.6 on 2024-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0030_alter_dcmpatient_address_alter_dcmpatient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmadmin',
            name='dcmadmin_department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dcmadmin',
            name='dcmadmin_full_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dcmadmin',
            name='dcmadmin_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
