# Generated by Django 4.2.6 on 2024-04-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0031_dcmadmin_dcmadmin_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendentProfile',
        ),
    ]
