# Generated by Django 4.2.6 on 2024-04-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('App_Login', '0032_delete_attendentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.department'),
        ),
    ]
