# Generated by Django 4.2.6 on 2024-04-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0033_technician_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcmAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('dcmadmin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcmadmin_profile', to='App_Login.dcmadmin')),
            ],
        ),
    ]
