# Generated by Django 4.2.6 on 2024-05-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0034_dcmadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
